### PR TITLE
44 feature/add tests

### LINKED ISSUE #43: Refactor 'Move by Taxonomy' Metabox into new code Architecture

### LINKED ISSUE #44: Add tests for 'Move by Custom Taxonomy' metabox
This needs to be done together with #43

### LINKED ISSUE #59: Add additional test cases to 'Move by Taxonomy' Module
Do this after #43

### PR DESCRIPTION
**Pull request by mariadanieldeepak**
**Note**: #43 must be merged before merging #44 

Close #43, close #44, close #59 and close sudar/wp-plugin-test-tools#1

### CODE REVIEW

**Comment by mariadanieldeepak** [comment]
@sudar,

Shall I merge `dev/2.0.0` into  `44-feature/add-tests` to solve conflicts?

**Comment by sudar** [comment]
@mariadanieldeepak sure, go ahead.

You may also have to change the base class of the test cases.

**Comment by mariadanieldeepak** [comment]
@sudar,

> You may also have to change the base class of the test cases.

Sure.

BTW, brilliant work including the helper methods to Bulk WP. I've a method that's needed for Bulk Move. Kindly merge that before merging this request. (PR here - sudar/wp-plugin-test-tools#1)

**Comment by sudar** [comment]
> BTW, brilliant work including the helper methods to Bulk WP. 

Glad you liked it.

> I've a method that's needed for Bulk Move. Kindly merge that before merging this request.

Merged.

You may have to do `composer update` and then check-in the `composer.lock` file to make travis build pass.

**Comment by mariadanieldeepak** [comment]
> You may have to do composer update and then check-in the composer.lock file to make travis build pass.

Done

**Comment by mariadanieldeepak** [comment]
@sudar,

Even after pushing the composer.lock file, the Travis CI build failed. Could you share some insights on how Travis CI works?

**Comment by sudar** [comment]
@mariadanieldeepak 

Merge the latest dev/2.0.0 branch and let me know if you are still facing issues.

**Comment by mariadanieldeepak** [comment]
@sudar,

Closing #49 closes #43. Since #49 has #44 changes, this PR is redundant. You may close this PR along with #44, once you merge #49.

**Pull request closed without merging**
